### PR TITLE
Small benchmarking script improvements

### PR DESCRIPTION
**Pull request by Zaczero**
During my recent testing I noticed a deprecation warning happening on the guid element check. Included in this PR instead of the previous #5 because I accidentally merged this change.

perf_counter provides higher resolution clock and is more suitable for benchmarking

There is a small time difference when accessing attributes in Python vs not. I have unified the parser usage pattern (fastfeedparse -> fastfeedparser.parse) to make the comparison more fair.

### CODE REVIEW

**Comment by Zaczero** [comment]
My editor automatically trims trailing whitespaces. If that's annoying to you please let me know so I can disable it for this project.

**Comment by vprelovac** [comment]
Thanks for these changes, I added few more feeds for benchmarking and further improved benchmarking logic.. looks like we are now at 11x avg speedup.

Ideally we would sample feeds  and keep the content inside repo so that benchmarks can be reproduced reliably.

**Comment by Zaczero** [comment]
> Thanks for these changes, I added few more feeds for benchmarking and further improved benchmarking logic.. looks like we are now at 11x avg speedup.

The library is faster on smal feeds. The longer they get, the more similar the results get which sounds reasonable.

> Ideally we would sample feeds  and keep the content inside repo so that benchmarks can be reproduced reliably.

Perhaps reuse the integration tests data? - which contains raw XML of feeds.

**Comment by vprelovac** [comment]
Sure. And if you have ideas for further speedups please feel free to drive them forward. Great contribution so far, very appreciated.

**Pull request merged**
